id: P009641
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-19 20:42:23.066485
source_metadata:
  id: bdr:W2DB4570
  title: གསུང་འབུམ（དཔེ་བསྡུར་མ）། ཀུན་དགའ་རྒྱལ་མཚན།
  author: ''
  volumes:
    381696965bb34b5199a0b1bac87f2346:
      image_group_id: I1PD34019
      title: ''
      volume_number: 1
      total_pages: 568
      base_file: v001.txt
    69dda6fdae15421cb3c75b3349b191b0:
      image_group_id: I1PD34020
      title: ''
      volume_number: 2
      total_pages: 518
      base_file: v002.txt
    7298f8a3c3f140fca3674bdca64aed2f:
      image_group_id: I1PD34021
      title: ''
      volume_number: 3
      total_pages: 462
      base_file: v003.txt
    264e0667f095427e8a3259d7b591e663:
      image_group_id: I1PD34022
      title: ''
      volume_number: 4
      total_pages: 348
      base_file: v004.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
