id: I7B4A1475
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T18:06:00+00:00'
last_modified: '2022-06-08T12:30:29.204620+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB4570
  title: གསུང་འབུམ（དཔེ་བསྡུར་མ）། ཀུན་དགའ་རྒྱལ་མཚན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6ED3:
      image_group_id: I1PD34019
      title: ''
      total_pages: 568
      order: 1
      base_file: 6ED3.txt
    9CDB:
      image_group_id: I1PD34020
      title: ''
      total_pages: 518
      order: 2
      base_file: 9CDB.txt
    080A:
      image_group_id: I1PD34021
      title: ''
      total_pages: 462
      order: 3
      base_file: 080A.txt
    31FF:
      image_group_id: I1PD34022
      title: ''
      total_pages: 348
      order: 4
      base_file: 31FF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
